#!/usr/bin/env bash
# Builds a single self-contained file: dist/amazon-expedition-3d.html
# The vendored runtime (three.min.js) is inlined, so the result can be
# double-clicked, emailed, zipped or dropped on any static host.
set -euo pipefail

cd "$(dirname "$0")"
mkdir -p dist

node - <<'NODE'
const fs = require('fs');

const html = fs.readFileSync('amazon_3d.html', 'utf8');
const lib  = fs.readFileSync('three.min.js', 'utf8').trim();
const tag  = '<script src="three.min.js"></script>';

if (!html.includes(tag)) {
  console.error('build: script tag not found in amazon_3d.html');
  process.exit(1);
}

const banner = '<!-- Amazon Expedition 3D - single-file build, generated by build.sh. -->\n'
             + '<!-- Game code (c) 2026 Hazem Soussi, MIT. Three.js r128 (c) Three.js Authors, MIT. -->\n';

const out = banner + html.replace(tag, '<script>\n' + lib + '\n</script>');
fs.writeFileSync('dist/amazon-expedition-3d.html', out);

const kb = n => (n / 1024).toFixed(0) + ' KB';
console.log('build: dist/amazon-expedition-3d.html  ' + kb(out.length));
NODE
